re-fix systemd templates
marvel-nccr/ansible-role-aiida pull request #50
Opened 2020-10-27 11:55 UTC by ltalirz

2020-10-29 12:20 UTC, chrisjsewell commented
hey you requested my review, but it looks like you are still working on this

2020-10-29 12:25 UTC, ltalirz commented
sorry, done! (tests finally pass) ;-)

2020-11-01 22:44 UTC, ltalirz commented
ping

2020-11-02 14:26 UTC, chrisjsewell commented
> Also re-fixes systemd templates which were effectively broken (during my manual tests, I somehow came to believe that %I was the right way - it turns out that %i seems to be... unfortunately the documentation of systemd doesn't really help)

So where are we at with this, I assume now that dashes are still an issue? https://github.com/marvel-nccr/ansible-role-aiida/pull/49#issue-509977388

2020-11-02 14:40 UTC, chrisjsewell commented
This also goes part way to closing https://github.com/marvel-nccr/quantum-mobile/issues/126.
Are these links to the v4 variants that gio mentions?

I will make a PR for https://github.com/marvel-nccr/ansible-role-quantum-espresso to change them there as well (plus update the repo).
I guess its good to have them there as well, for standalone purposes (or could just remove them)?
But at least set the default in quantum-mobile to `quantum_espresso_pps: []` so that we don't duplicate the download

2020-11-02 14:41 UTC, chrisjsewell requested changes
code looks fine ta, but see questions in comments

2020-11-26 03:45 UTC, chrisjsewell approved these changes

2020-11-26 03:46 UTC, merged